# Generated by Django 5.0.14 on 2026-09-22 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit or Barcode', max_length=50, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase/Cost price', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail selling price', max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0, help_text='Current available stock; modified only via StockMovement')),
                ('reorder_level', models.IntegerField(default=5, help_text='Minimum threshold before triggering low-stock alert')),
                ('is_active', models.BooleanField(default=True, help_text='Active products appear in sales and catalog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity delta: positive for incoming/stock_in, positive/negative for adjustments')),
                ('reference', models.CharField(blank=True, help_text='e.g. Supplier invoice, Sale INV-0001, Correction', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
