# Generated by Django 5.0.14 on 2026-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retail selling price', max_digits=10, null=True),
        ),
    ]
