# Generated by Django 5.0.14 on 2026-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Purchase/Cost price', max_digits=10, null=True),
        ),
    ]
