# Generated by Django 5.0.14 on 2026-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name', max_length=200)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone / Mobile contact', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Email address', max_length=254)),
                ('address', models.TextField(blank=True, default='', help_text='Physical or postal address')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
